In [18]:
%cd /content

import os

# 1. 准备项目代码
REPO_DIR = "/content/bird-drone-dualstream"
REPO_URL = "https://github.com/uoi1398/bird-drone-dualstream.git"

if not os.path.exists(REPO_DIR):
    print("Repo not found. Cloning...")
    !git clone {REPO_URL}
else:
    print("Repo already exists. Pulling latest changes...")
    %cd {REPO_DIR}
    !git pull
    %cd /content

# 2. 准备公开数据集
DATASET_DIR = "/content/Drone-detection-dataset"
DATASET_URL = "https://github.com/DroneDetectionThesis/Drone-detection-dataset.git"

if not os.path.exists(DATASET_DIR):
    print("Dataset not found. Cloning...")
    !git clone {DATASET_URL}
else:
    print("Dataset already exists. Skip downloading.")

# 3. 进入项目目录
%cd {REPO_DIR}

# 4. 链接数据集
!mkdir -p data
!rm -rf data/raw
!ln -s /content/Drone-detection-dataset/Data data/raw

print("Current directory:")
!pwd

print("\nProject files:")
!ls

print("\nData raw:")
!ls data/raw

/content
Repo already exists. Pulling latest changes...
/content/bird-drone-dualstream
Already up to date.
/content
Dataset already exists. Skip downloading.
/content/bird-drone-dualstream
Current directory:
/content/bird-drone-dualstream

Project files:
configs  data  notebooks  README.md  requirements.txt  src

Data raw:
Audio					   Video_IR
Create_a_dataset_from_videos_and_labels.m  Video_V
Video_dataset_description.xlsx

In [12]:
%cd /content

import os

REPO_DIR = "/content/bird-drone-dualstream"
REPO_URL = "https://github.com/uoi1398/bird-drone-dualstream.git"

if not os.path.exists(REPO_DIR):
    print("Repo not found. Cloning from GitHub...")
    !git clone {REPO_URL}
else:
    print("Repo already exists. Pulling latest changes...")
    %cd {REPO_DIR}
    !git pull
    %cd /content

%cd {REPO_DIR}

print("Current directory:")
!pwd

print("\nProject files:")
!ls

/content
Repo already exists. Pulling latest changes...
/content/bird-drone-dualstream
Already up to date.
/content
/content/bird-drone-dualstream
Current directory:
/content/bird-drone-dualstream

Project files:
configs  notebooks  README.md  requirements.txt  src

In [14]:
from pathlib import Path
import os
import random
import pandas as pd
import numpy as np

import sys
sys.path.append("/content/bird-drone-dualstream/src")

from dataset import BirdDroneVideoDataset

print("Imports OK.")

Imports OK.

In [16]:
%cd /content

import os

DATASET_DIR = "/content/Drone-detection-dataset"
DATASET_URL = "https://github.com/DroneDetectionThesis/Drone-detection-dataset.git"

if not os.path.exists(DATASET_DIR):
    print("Dataset not found. Cloning Drone-detection-dataset...")
    !git clone {DATASET_URL}
else:
    print("Dataset already exists.")

print("Check dataset directory:")
!ls /content
!ls /content/Drone-detection-dataset

/content
Dataset not found. Cloning Drone-detection-dataset...
Cloning into 'Drone-detection-dataset'...
remote: Enumerating objects: 1572, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 1572 (delta 55), reused 110 (delta 52), pack-reused 1457 (from 1)
Receiving objects: 100% (1572/1572), 291.86 MiB | 29.17 MiB/s, done.
Resolving deltas: 100% (99/99), done.
Updating files: 100% (1396/1396), done.
Check dataset directory:
bird-drone-dualstream  drive  Drone-detection-dataset  sample_data
Data  Demo_IR_DRONE_146.mp4  Demo_V_DRONE_017.mp4  LICENSE  README.md

In [17]:
DATASET_ROOT = Path("/content/Drone-detection-dataset")
DATA_ROOT = DATASET_ROOT / "Data"

print("DATASET_ROOT exists:", DATASET_ROOT.exists())
print("DATA_ROOT exists:", DATA_ROOT.exists())

!find /content/Drone-detection-dataset -maxdepth 2 -type d

DATASET_ROOT exists: True
DATA_ROOT exists: True
/content/Drone-detection-dataset
/content/Drone-detection-dataset/.git
/content/Drone-detection-dataset/.git/branches
/content/Drone-detection-dataset/.git/refs
/content/Drone-detection-dataset/.git/hooks
/content/Drone-detection-dataset/.git/info
/content/Drone-detection-dataset/.git/logs
/content/Drone-detection-dataset/.git/objects
/content/Drone-detection-dataset/Data
/content/Drone-detection-dataset/Data/Video_V
/content/Drone-detection-dataset/Data/Video_IR
/content/Drone-detection-dataset/Data/Audio

In [19]:
%cd /content/bird-drone-dualstream

!mkdir -p data

# 删除旧 raw 链接或旧 raw 文件夹
!rm -rf data/raw

# 把公开数据集中的 Data 目录链接到项目 data/raw
!ln -s /content/Drone-detection-dataset/Data data/raw

print("Check data directory:")
!ls -l data

print("\nCheck data/raw:")
!ls data/raw

/content/bird-drone-dualstream
Check data directory:
total 0
lrwxrwxrwx 1 root root 37 May 16 07:04 raw -> /content/Drone-detection-dataset/Data

Check data/raw:
Audio					   Video_IR
Create_a_dataset_from_videos_and_labels.m  Video_V
Video_dataset_description.xlsx

In [20]:
from pathlib import Path

DATA_ROOT = Path("data/raw")

VIDEO_EXTS = [".mp4", ".avi", ".mov", ".mkv"]

def collect_all_videos(root, video_exts):
    videos = []
    for ext in video_exts:
        videos.extend(root.rglob(f"*{ext}"))
    return sorted(videos)

all_videos = collect_all_videos(DATA_ROOT, VIDEO_EXTS)

print("All videos:", len(all_videos))

print("\nFirst 20 videos:")
for p in all_videos[:20]:
    print(p)

All videos: 650

First 20 videos:
data/raw/Video_IR/IR_AIRPLANE_001.mp4
data/raw/Video_IR/IR_AIRPLANE_002.mp4
data/raw/Video_IR/IR_AIRPLANE_003.mp4
data/raw/Video_IR/IR_AIRPLANE_004.mp4
data/raw/Video_IR/IR_AIRPLANE_005.mp4
data/raw/Video_IR/IR_AIRPLANE_006.mp4
data/raw/Video_IR/IR_AIRPLANE_007.mp4
data/raw/Video_IR/IR_AIRPLANE_008.mp4
data/raw/Video_IR/IR_AIRPLANE_009.mp4
data/raw/Video_IR/IR_AIRPLANE_010.mp4
data/raw/Video_IR/IR_AIRPLANE_011.mp4
data/raw/Video_IR/IR_AIRPLANE_012.mp4
data/raw/Video_IR/IR_AIRPLANE_013.mp4
data/raw/Video_IR/IR_AIRPLANE_014.mp4
data/raw/Video_IR/IR_AIRPLANE_015.mp4
data/raw/Video_IR/IR_AIRPLANE_016.mp4
data/raw/Video_IR/IR_AIRPLANE_017.mp4
data/raw/Video_IR/IR_AIRPLANE_018.mp4
data/raw/Video_IR/IR_AIRPLANE_019.mp4
data/raw/Video_IR/IR_AIRPLANE_020.mp4

In [21]:
visible_videos = [
    p for p in all_videos
    if "VIDEO_V" in str(p).upper()
]

print("Visible videos:", len(visible_videos))

print("\nFirst 20 visible videos:")
for p in visible_videos[:20]:
    print(p)

Visible videos: 285

First 20 visible videos:
data/raw/Video_V/V_AIRPLANE_001.mp4
data/raw/Video_V/V_AIRPLANE_002.mp4
data/raw/Video_V/V_AIRPLANE_003.mp4
data/raw/Video_V/V_AIRPLANE_004.mp4
data/raw/Video_V/V_AIRPLANE_005.mp4
data/raw/Video_V/V_AIRPLANE_006.mp4
data/raw/Video_V/V_AIRPLANE_007.mp4
data/raw/Video_V/V_AIRPLANE_008.mp4
data/raw/Video_V/V_AIRPLANE_009.mp4
data/raw/Video_V/V_AIRPLANE_010.mp4
data/raw/Video_V/V_AIRPLANE_011.mp4
data/raw/Video_V/V_AIRPLANE_012.mp4
data/raw/Video_V/V_AIRPLANE_013.mp4
data/raw/Video_V/V_AIRPLANE_014.mp4
data/raw/Video_V/V_AIRPLANE_015.mp4
data/raw/Video_V/V_AIRPLANE_016.mp4
data/raw/Video_V/V_AIRPLANE_017.mp4
data/raw/Video_V/V_AIRPLANE_018.mp4
data/raw/Video_V/V_AIRPLANE_019.mp4
data/raw/Video_V/V_AIRPLANE_020.mp4

In [22]:
bird_videos = [
    p for p in visible_videos
    if "BIRD" in p.name.upper()
]

drone_videos = [
    p for p in visible_videos
    if "DRONE" in p.name.upper()
]

print("Bird visible videos:", len(bird_videos))
print("Drone visible videos:", len(drone_videos))

print("\nExample bird videos:")
for p in bird_videos[:5]:
    print(p)

print("\nExample drone videos:")
for p in drone_videos[:5]:
    print(p)

Bird visible videos: 51
Drone visible videos: 114

Example bird videos:
data/raw/Video_V/V_BIRD_001.mp4
data/raw/Video_V/V_BIRD_002.mp4
data/raw/Video_V/V_BIRD_003.mp4
data/raw/Video_V/V_BIRD_004.mp4
data/raw/Video_V/V_BIRD_005.mp4

Example drone videos:
data/raw/Video_V/V_DRONE_001.mp4
data/raw/Video_V/V_DRONE_002.mp4
data/raw/Video_V/V_DRONE_003.mp4
data/raw/Video_V/V_DRONE_004.mp4
data/raw/Video_V/V_DRONE_005.mp4

In [23]:
assert len(bird_videos) == 51, f"Expected 51 bird videos, got {len(bird_videos)}"
assert len(drone_videos) == 114, f"Expected 114 drone videos, got {len(drone_videos)}"

print("Video counts are correct.")

Video counts are correct.

In [26]:
import random
import pandas as pd

SEED = 42
random.seed(SEED)

bird_videos_shuffled = bird_videos.copy()
drone_videos_shuffled = drone_videos.copy()

random.shuffle(bird_videos_shuffled)
random.shuffle(drone_videos_shuffled)

records = []

def add_records(video_paths, label, label_name, train_n, val_n, test_n):
    assert len(video_paths) == train_n + val_n + test_n

    split_names = (
        ["train"] * train_n +
        ["val"] * val_n +
        ["test"] * test_n
    )

    for path, split in zip(video_paths, split_names):
        records.append({
            "video_id": path.stem,
            "path": str(path),
            "label": label,
            "label_name": label_name,
            "split": split
        })

# bird = 0, drone = 1
add_records(
    bird_videos_shuffled,
    label=0,
    label_name="bird",
    train_n=36,
    val_n=7,
    test_n=8
)

add_records(
    drone_videos_shuffled,
    label=1,
    label_name="drone",
    train_n=79,
    val_n=18,
    test_n=17
)

manifest = pd.DataFrame(records)

display(manifest.head())

print("Total samples:", len(manifest))

print("\nSplit x label:")
print(pd.crosstab(manifest["split"], manifest["label_name"]))

     video_id                             path  label label_name  split
0  V_BIRD_026  data/raw/Video_V/V_BIRD_026.mp4      0       bird  train
1  V_BIRD_024  data/raw/Video_V/V_BIRD_024.mp4      0       bird  train
2  V_BIRD_020  data/raw/Video_V/V_BIRD_020.mp4      0       bird  train
3  V_BIRD_012  data/raw/Video_V/V_BIRD_012.mp4      0       bird  train
4  V_BIRD_005  data/raw/Video_V/V_BIRD_005.mp4      0       bird  train

Total samples: 165

Split x label:
label_name  bird  drone
split
test           8     17
train         36     79
val            7     18

In [27]:
import os

os.makedirs("data/splits", exist_ok=True)

manifest_path = "data/splits/manifest.csv"
manifest.to_csv(manifest_path, index=False)

print("Saved manifest to:", manifest_path)

!ls -l data/splits

Saved manifest to: data/splits/manifest.csv
total 12
-rw-r--r-- 1 root root 9544 May 16 07:06 manifest.csv

In [28]:
df = pd.read_csv("data/splits/manifest.csv")

print("Head:")
display(df.head())

print("\nColumns:")
print(df.columns.tolist())

print("\nTotal samples:", len(df))

print("\nLabel counts:")
print(df["label_name"].value_counts())

print("\nSplit counts:")
print(df["split"].value_counts())

print("\nSplit x label:")
print(pd.crosstab(df["split"], df["label_name"]))

Head:

     video_id                             path  label label_name  split
0  V_BIRD_026  data/raw/Video_V/V_BIRD_026.mp4      0       bird  train
1  V_BIRD_024  data/raw/Video_V/V_BIRD_024.mp4      0       bird  train
2  V_BIRD_020  data/raw/Video_V/V_BIRD_020.mp4      0       bird  train
3  V_BIRD_012  data/raw/Video_V/V_BIRD_012.mp4      0       bird  train
4  V_BIRD_005  data/raw/Video_V/V_BIRD_005.mp4      0       bird  train

Columns:
['video_id', 'path', 'label', 'label_name', 'split']

Total samples: 165

Label counts:
label_name
drone    114
bird      51
Name: count, dtype: int64

Split counts:
split
train    115
val       25
test      25
Name: count, dtype: int64

Split x label:
label_name  bird  drone
split
test           8     17
train         36     79
val            7     18

In [29]:
df["path_exists"] = df["path"].apply(os.path.exists)

print(df["path_exists"].value_counts())

missing = df[~df["path_exists"]]

if len(missing) > 0:
    print("Missing files:")
    display(missing.head(20))
else:
    print("All video paths exist.")

assert df["path_exists"].all(), "Some video paths do not exist."

path_exists
True    165
Name: count, dtype: int64
All video paths exist.

In [30]:
rgb_ds = BirdDroneVideoDataset(
    csv_path="data/splits/manifest.csv",
    split="train",
    mode="rgb",
    num_frames=16,
    image_size=224,
    degrade_level="none"
)

x, y, video_id = rgb_ds[0]

print("RGB tensor shape:", x.shape)
print("Label:", y)
print("Video ID:", video_id)

RGB tensor shape: torch.Size([16, 3, 224, 224])
Label: tensor(0)
Video ID: V_BIRD_026

In [31]:
flow_ds = BirdDroneVideoDataset(
    csv_path="data/splits/manifest.csv",
    split="train",
    mode="flow",
    num_frames=8,
    image_size=160,
    degrade_level="none"
)

x_flow, y_flow, video_id_flow = flow_ds[0]

print("Flow tensor shape:", x_flow.shape)
print("Label:", y_flow)
print("Video ID:", video_id_flow)

Flow tensor shape: torch.Size([7, 3, 160, 160])
Label: tensor(0)
Video ID: V_BIRD_026

In [32]:
rgb_degraded_ds = BirdDroneVideoDataset(
    csv_path="data/splits/manifest.csv",
    split="train",
    mode="rgb",
    num_frames=16,
    image_size=224,
    degrade_level="strong"
)

x_deg, y_deg, video_id_deg = rgb_degraded_ds[0]

print("Degraded RGB tensor shape:", x_deg.shape)
print("Label:", y_deg)
print("Video ID:", video_id_deg)

Degraded RGB tensor shape: torch.Size([16, 3, 224, 224])
Label: tensor(0)
Video ID: V_BIRD_026

In [33]:
print("Data check finished successfully.")
print("Manifest path: data/splits/manifest.csv")
print("Ready for training RGB and Flow models.")

Data check finished successfully.
Manifest path: data/splits/manifest.csv
Ready for training RGB and Flow models.